Feature/ping server daemon
SkoltechSummerCamp/sandbox pull request #5
Opened 2021-08-06 17:05 UTC by nikonufrienko

2021-08-06 19:39 UTC, AdvancerMan requested changes

2021-08-06 19:39 UTC, AdvancerMan commented on pingCheck.iml
> +</module>
Еще один файл IDE. Его лучше добавить в `.git/info/exclude`, так как название проекта у коллег может отличаться (если я правильно понял, название файла = название проекта).

2021-08-06 19:39 UTC, AdvancerMan commented on src/Main.java
> +    static PingCheckServer pcs;
Скорее всего, тут имеется в виду модификатор `private`

2021-08-06 19:39 UTC, AdvancerMan commented on src/PingCheckServer.java
> +    int port;
`private`

2021-08-06 19:39 UTC, AdvancerMan commented on src/PingCheckServer.java
> +    public PingCheckServer(int port) throws SocketException {
Лишний `throws`?

2021-08-06 19:39 UTC, AdvancerMan commented on src/PingCheckServer.java
> +                    byte[] inputBuffer = new byte[1024];
Создаешь буффер на каждой итерации

2021-08-06 19:39 UTC, AdvancerMan commented on src/PingCheckServer.java
> +                    DatagramPacket inputPacket = new DatagramPacket(inputBuffer, 1024);
Дублирование длины буффера

2021-08-06 19:39 UTC, AdvancerMan commented on src/PingCheckServer.java
> +        while (!isInterrupted()) {
Странный цикл: после `IOException` ты снова пытаешься возобновить работу. Скорее всего ты не хочешь этого делать. Например, на машине пропал интернет или ОС не разрешила тебе взять выбранный порт. Из-за этого ты бесконечно будешь делать ничего, что плохо

2021-08-06 22:54 UTC, nikonufrienko commented on pingCheck.iml
> +</module>
Удалил.

2021-08-06 22:55 UTC, nikonufrienko commented on src/Main.java
> +    static PingCheckServer pcs;
Ок

2021-08-06 22:55 UTC, nikonufrienko commented on src/PingCheckServer.java
> +    int port;
Ок

2021-08-06 22:55 UTC, nikonufrienko commented on src/PingCheckServer.java
> +    public PingCheckServer(int port) throws SocketException {
Ок

2021-08-06 22:55 UTC, nikonufrienko commented on src/PingCheckServer.java
> +                    byte[] inputBuffer = new byte[1024];
Исправил.

2021-08-06 22:55 UTC, nikonufrienko commented on src/PingCheckServer.java
> +                    DatagramPacket inputPacket = new DatagramPacket(inputBuffer, 1024);
Ок, выделю под это дело переменную.

2021-08-06 22:55 UTC, nikonufrienko commented on src/PingCheckServer.java
> +        while (!isInterrupted()) {
Ок, убрал внешний цикл-некроманта.

2021-08-07 05:57 UTC, AdvancerMan reviewed
Все остальное ок

2021-08-07 05:57 UTC, AdvancerMan commented on src/PingCheckServer.java
> +    }
Я вижу тут 2 проблемы:

1. Тред не успел запуститься, но уже интерраптится --- `serverSocket = null`, вызов падает с `NullPointerException`;
2. Другой тред [может не увидеть](https://docs.oracle.com/javase/tutorial/essential/concurrency/atomic.html) изменения `serverSocket`. Это исправится модификатором `volatile`.

2021-08-07 05:57 UTC, AdvancerMan commented on src/PingCheckServer.java
> +    }
И еще: после интеррапта в любом случае сокет будет закрыт хотя бы 2 раза. К счастью, это не проблема: если посмотреть в сорцы джавы, можно увидеть проверку закрыт ли сокет. Но в документации я такого поведения не нашел. Если ты что-то знаешь по этому поводу, сообщи.

2021-08-07 07:03 UTC, nikonufrienko commented on src/PingCheckServer.java
> +    }
Разве volatile  не работает только с примитивными типами? Неужели применение volotile к объекту делает его атомарным? Мне казалось, что в таком случае потокобезопасной становится только ссылка на объект.

2021-08-07 09:01 UTC, nikonufrienko commented on src/PingCheckServer.java
> +    }
Вызывая метод `.interrupt()` мы вешаем флаг, однако поток сам не закроется по причине того, что он скорее всего будет заблокирован в методе `.receive()`. Именно поэтому необходимо закрывать сокет в перегруженном методе `.interrupt()`. Второго закрытия быть не должно, поскольку метод `.close()` у класса Closeable является идемпотентным в отличии от autoClosable.

2021-08-07 13:52 UTC, AdvancerMan commented on src/PingCheckServer.java
> +    }
Да, ты прав, потокобезопасной станет только ссылка на объект, но это нам и надо. `volatile` это не только про атомарность, но и про отношение `happens-before` между последовательными чтениями и записями. Почему это важно, можно почитать [здесь](https://docs.oracle.com/javase/tutorial/essential/concurrency/memconsist.html). В данном случае мы хотим, чтобы _чтение ссылки в методе `interrupt()`_ `happens-before` _запись ссылки в переменную в методе `run`_.

Про `Closeable` увидел, спасибо!

2021-08-07 14:13 UTC, AdvancerMan commented on .gitignore
> +/META-INF/
Кстати, я предполагаю, что в папке `META-INF` ты хранишь манифест для сборки `jar` файла. Если это правда, то было бы удобно иметь его в репозитории, чтобы настроить автоматическую сборку через GitHub Actions.

2021-08-09 11:22 UTC, merged