Feature/speedtest app
SkoltechSummerCamp/sandbox pull request #7
Opened 2021-08-10 14:16 UTC by nikonufrienko

2021-08-11 10:13 UTC, AdvancerMan requested changes

2021-08-11 10:13 UTC, AdvancerMan commented on app/src/main/java/com/company/test/ICMPPing.kt
> +            Log.d("", "external interruption")
Давай давать непустые теги при логгировании

2021-08-11 10:13 UTC, AdvancerMan commented on app/src/main/java/com/company/test/ICMPPing.kt
> +        }
Копипаста

2021-08-11 10:13 UTC, AdvancerMan commented on app/src/main/java/com/company/test/MainActivity.kt
> +    }
`ICMPPing` и `justICMPPing` очень похожи, попробуй как-нибудь обобщить

2021-08-11 10:13 UTC, AdvancerMan commented on app/src/main/java/com/company/test/MainActivity.kt
> +    private val PING_SERVER_UDP_PORT = 49121
Немного странно, что `MainActivity` что-то знает про порт сервера. Как-то не Single Responsibility получается

2021-08-11 10:13 UTC, AdvancerMan commented on app/src/main/java/com/company/test/MainActivity.kt
> +    private val PING_SERVER_UDP_PORT = 49121
И еще: это константа, поэтому вынеси ее в `companion object` (или сделай `static final` в джаве)

2021-08-11 10:13 UTC, AdvancerMan commented on app/src/main/java/com/company/test/MainActivity.kt
> +                    }
Выглядит как активное ожидание

2021-08-11 10:13 UTC, AdvancerMan commented on app/src/main/java/com/company/test/PingCheckClient.java
> +            DatagramPacket inputDatagramPacket = new DatagramPacket(new byte[1024], 1024);
Дублирование длины буффера

2021-08-11 10:13 UTC, AdvancerMan commented on app/src/main/java/com/company/test/PingCheckClient.java
> +                return -1;
Давай всегда ставить скобки в `if` (за исключением тернарного). Лучше придерживться одного стиля (чуть выше почему-то эти скобки есть).

2021-08-11 10:13 UTC, AdvancerMan commented on app/src/main/java/com/company/test/pingChecker.kt
> +) {
Давай сделаем эту функцию частью класса `PingCheckClient`, либо объясни, почему так не надо

2021-08-11 10:13 UTC, AdvancerMan commented on app/src/main/java/com/company/test/pingChecker.kt
> +    currValueSetter: (String) -> Unit,
Лямбды обычно ставят последним аргументом

2021-08-11 10:13 UTC, AdvancerMan commented on app/src/main/java/com/company/test/pingChecker.kt
> +        }
`String.format("%.2f", it)`, если я правильно понял

2021-08-11 10:13 UTC, AdvancerMan commented on app/src/main/java/com/company/test/ICMPPing.kt
> +    fun justPingByHost(host: String, currValueGetter: (String) -> Unit) {
Геттер обычно что-то возвращает, а тут только бесполезный `Unit`

2021-08-11 10:24 UTC, AdvancerMan commented on app/src/main/java/com/company/test/MainActivity.kt
> +                    }
Сорри, busy waiting называется. Сделай что-то вроде джавовского `wait` и `notify`

2021-08-11 22:30 UTC, nikonufrienko commented on app/src/main/java/com/company/test/ICMPPing.kt
> +    fun justPingByHost(host: String, currValueGetter: (String) -> Unit) {
Он забирает. Ладно переименую его в taker.

2021-08-11 22:34 UTC, nikonufrienko commented on app/src/main/java/com/company/test/MainActivity.kt
> +                    }
`delay(10)` сверху приостанавливает корутину на 10ms.

2021-08-11 22:36 UTC, nikonufrienko commented on app/src/main/java/com/company/test/PingCheckClient.java
> +                return -1;
Ладно... (Скобки могли просто остаться после удаления лишних логов.)

2021-08-11 22:45 UTC, nikonufrienko commented on app/src/main/java/com/company/test/pingChecker.kt
> +) {
Ладно, могу сделать.

2021-08-11 22:45 UTC, nikonufrienko commented on app/src/main/java/com/company/test/pingChecker.kt
> +    currValueSetter: (String) -> Unit,
Ок, исправлю.

2021-08-11 22:46 UTC, nikonufrienko commented on app/src/main/java/com/company/test/pingChecker.kt
> +        }
ок

2021-08-11 22:52 UTC, nikonufrienko commented on app/src/main/java/com/company/test/MainActivity.kt
> +    }
Сделаю.

2021-08-11 22:59 UTC, nikonufrienko commented on app/src/main/java/com/company/test/ICMPPing.kt
> +        }
Ок, попробую их объединить воедино, на вход будет подаваться enum указывающий на режим работы.

2021-08-12 07:15 UTC, AdvancerMan commented on app/src/main/java/com/company/test/ICMPPing.kt
> +        }
Имхо, ифание enum'а -- не самый лучший вариант. Предлагаю сделать функцию `f`, которая принимает аргументы для пинга и лямбду, которая обрабатывает строки из вывода. Тогда `f` будет вызываться в `performPingWithArgs` и `justPingByHost`. Либо вызывать `f` вместо вызовов `performPingWithArgs` и `justPingByHost` (вроде они у тебя 1 раз вызываются)

2021-08-12 07:45 UTC, AdvancerMan commented on app/src/main/java/com/company/test/MainActivity.kt
> +                    }
Тем не менее, каждые 10 мс. ты тратишь время процессора, чтобы проверить изменился ли буффер (в `pingTestButtonAction` ты делаешь это каждую мс.). У `Activity` есть прекрасный метод `runOnUiThread`. В нем можно изменять текст `pingValue` именно в тот момент, в который он действительно меняется. Кстати, флажок `justICMPPingInChecking` скорее нужно перенести в класс `ICMPPing`. Также вместо `justStopICMPPingFlag = false`, лучше делать сразу `pinger.stopExecuting()`

2021-08-12 07:51 UTC, AdvancerMan requested changes

2021-08-12 07:51 UTC, AdvancerMan commented on app/src/main/java/com/company/test/ICMPPing.kt
> +    }
Я не уверен, но, возможно, после `IOException` процесс `sh` не будет остановлен

2021-08-17 18:21 UTC, closed without merging