initial commit. Add new project with demo mode
SkoltechSummerCamp/sandbox pull request #8
Opened 2021-08-16 09:19 UTC by CatherineChernogor

Add a main screen for demonstration mode with new ux design. The main screen can be in 2 different state: starting - when user have to push play button, and working state when app mock activity with file data. Data was collected as output for iperf command

2021-08-17 13:48 UTC, AdvancerMan requested changes
Как я понимаю, мы потом будем мерджить это с остальным `SpeedtestApplication`, поэтому замечания в файлах `build.gradle` можешь не исправлять

2021-08-17 13:48 UTC, AdvancerMan commented on .gitignore
> +/.idea/assetWizardSettings.xml
Почему не вся папка `.idea`? Файла `build.gradle` достаточно, чтобы работать с проектом.

2021-08-17 13:48 UTC, AdvancerMan commented on app/.gitignore
> +/build
В репозиторий попал `app/release/app-release.apk`. Имхо, имеет смысл заигнорить папку `app/release`.

2021-08-17 13:48 UTC, AdvancerMan commented on app/build.gradle
> +        applicationId "com.example.wavemockapplication"
У нас `applicationId = ru.scoltech.openran.speedtest`

2021-08-17 13:48 UTC, AdvancerMan commented on build.gradle
> +        jcenter()
Недавно репозиторий `jcenter` [стал read-only](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). Можно его заменить, например, на `mavenCentral`

2021-08-17 13:48 UTC, AdvancerMan commented on app/src/main/java/com/example/wavemockapplication/CardView.java
> +    String mStatus;
Видимо, имеется в виду модификатор `private`

2021-08-17 13:48 UTC, AdvancerMan commented on app/src/main/java/com/example/wavemockapplication/CardView.java
> +    String mStatus;
Так же поля `fractionSpeed`, `integerSpeed`, `ping`, кажется можно заменить на локальные переменные (где этот код используется в демке я не увидел -- возможно у них появится смысл)

2021-08-17 13:48 UTC, AdvancerMan commented on app/src/main/java/com/example/wavemockapplication/HeaderView.java
> +        } catch (Exception e) {
`catch Exception` обычно плохая идея

2021-08-17 13:48 UTC, AdvancerMan commented on app/src/main/java/com/example/wavemockapplication/MainActivity.java
> +                    }, TASK_DELAY);
`minSdkVersion` у тебя `27` -- там уже есть лямбды. Например, этот код можно переписать так: `() -> { // ... code ... }`

2021-08-17 13:48 UTC, AdvancerMan commented on app/src/main/java/com/example/wavemockapplication/MainActivity.java
> +        final int[] i = {0};
Не очень понятно, зачем инт обернут в массив

2021-08-17 13:48 UTC, AdvancerMan commented on app/src/main/java/com/example/wavemockapplication/SpeedManager.java
> +            int frac_speed = Integer.parseInt(speed) % 1000000;
Парсишь строку 2 раза

2021-08-17 13:48 UTC, AdvancerMan commented on app/src/main/java/com/example/wavemockapplication/SpeedManager.java
> +        }
`downloadList.addAll(list.subList(0, list.size() / 2));`

2021-08-17 13:48 UTC, AdvancerMan commented on app/src/main/java/com/example/wavemockapplication/SpeedManager.java
> +    public List<String> downloadList;
В джаве принято делать поля приватными, а иметь доступ к ним через геттеры/сеттеры

2021-08-17 13:48 UTC, AdvancerMan commented on app/src/main/java/com/example/wavemockapplication/SpeedManager.java
> +                sum += Integer.parseInt(sp.substring(0, sp.length() - 3));
Имхо `Integer.parseInt(sp) / 1000` будет понятнее

2021-08-17 13:55 UTC, AdvancerMan commented on app/src/main/java/com/example/wavemockapplication/SpeedManager.java
> +    public List<String> downloadList;
В Android Studio, кстати, можно автоматически сгенерировать эти методы с помощью комбинации клавиш `Alt + Insert`

2021-08-17 17:04 UTC, AdvancerMan commented on app/src/main/java/com/example/wavemockapplication/Activities/MainActivity.java
> +package com.example.wavemockapplication.Activities;
Когда я говорил про `applicationId`, я также имел в виду пекеджи. Например, этот должен превратиться в `ru.scoltech.openran.speedtest.Activities`. Также пекеджи в джаве именуют camelCase'ом, то есть директорию `Activities` лучше переименовать в `activities`

2021-08-20 10:51 UTC, CatherineChernogor commented on app/src/main/java/com/example/wavemockapplication/MainActivity.java
> +        final int[] i = {0};
Это по сути своей счетчик, но он используется во внутренем классе поэтому он должен был быть final, но если он final то тогда логично, что его нельзя изменять. Поэтому я обернула счетчик в массив, получается что ссылка одна и та же но значение можно изменять

Но кстати я не подумала, что его можно ниже как поле у класса runnable объявить, и так кстати работает

2021-08-20 13:28 UTC, merged